version: '3.8'

services:
    monogo-db-service:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: development
        networks:
            - application